name: Build and Release

on:
  push:
    branches: [main]
    tags: ['v*']
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  DOTNET_VERSION: '8.0.x'
  BUILD_CONFIGURATION: Release

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, aarch64, armv7]
        include:
          - arch: amd64
            runtime: linux-musl-x64
          - arch: aarch64
            runtime: linux-musl-arm64
          - arch: armv7
            runtime: linux-musl-arm

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Restore dependencies
      run: dotnet restore src/CasaBot.csproj
    
    - name: Build
      run: dotnet build src/CasaBot.csproj --no-restore --configuration ${{ env.BUILD_CONFIGURATION }}
    
    - name: Publish
      run: |
        dotnet publish src/CasaBot.csproj \
          --configuration ${{ env.BUILD_CONFIGURATION }} \
          --runtime ${{ matrix.runtime }} \
          --self-contained true \
          --output ./publish/${{ matrix.arch }}
    
    - name: Create package
      run: |
        cd ./publish/${{ matrix.arch }}
        tar -czf ../casabot-${{ matrix.arch }}.tar.gz .
        cd ..
        sha256sum casabot-${{ matrix.arch }}.tar.gz > casabot-${{ matrix.arch }}.tar.gz.sha256
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: casabot-${{ matrix.arch }}
        path: |
          ./publish/casabot-${{ matrix.arch }}.tar.gz
          ./publish/casabot-${{ matrix.arch }}.tar.gz.sha256

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: ./artifacts

    - name: Prepare release assets
      run: |
        mkdir -p ./release-assets
        find ./artifacts -name "*.tar.gz*" -exec cp {} ./release-assets/ \;

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: ./release-assets/*
        draft: false
        prerelease: false
        generate_release_notes: true