# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.15"
  amd64: "ghcr.io/home-assistant/amd64-base:3.15"
  armv7: "ghcr.io/home-assistant/armv7-base:3.15"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Casa Bot add-on"
  org.opencontainers.image.description: "Casa Bot add-on to interact with hassio with an LLM."
  org.opencontainers.image.source: "https://github.com/jmservera/casa-bot"
  org.opencontainers.image.licenses: "MIT"
args:
  TEMPIO_VERSION: "2021.09.0"