name: "Casa Bot"
description: "An LLM enabled bot to interact with Home Assitant's MCP server"
version: "0.1.14"
slug: "casabot"
init: false
ingress: true
auth_api: true
panel_icon: mdi:robot
panel_title: "Casa Bot"
map:
  - addon_config:rw
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
ports:
  8080/tcp: 8000
ports_description:
  8000/tcp: "Web UI"
image: "ghcr.io/jmservera/{arch}-addon-casabot"
options:
  system_packages: []
  init_commands: []
schema:
  leave_front_door_open: bool?
  system_packages:
    - str
  init_commands:
    - str