name: "Casa Bot"
description: "An LLM enabled bot to interact with Home Assitant's MCP server"
version: "0.1.8"
slug: "casabot"
init: false
ingress: true
ingress_port: 80
panel_icon: mdi:robot
panel_title: "Casa Bot"
arch:
  - aarch64
  - amd64
  - armv7
startup: services
ports:
  8080/tcp: 80
ports_description:
  8080/tcp: "Web UI (direct access)"
image: "ghcr.io/jmservera/{arch}-addon-casabot"
