name: "Casa Bot"
description: "An LLM enabled bot to interact with Home Assitant's MCP server"
version: "0.1.0"
slug: "casa_bot"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
ports:
  8000/tcp: 8000
image: "ghcr.io/jmservera/{arch}-addon-casa_bot"