name: "Casa Bot"
description: "An LLM enabled bot to interact with Home Assitant's MCP server"
version: "v0.2.9"
slug: "casabot"
ingress: true
auth_api: true
panel_icon: mdi:robot
panel_title: "Casa Bot"
homeassistant_api: true
init: false
map:
  - config:rw
  - share:rw
arch:
  - aarch64
  - amd64
  - armv7
startup: services
ports:
  8080/tcp: 8000
ports_description:
  8080/tcp: "Web UI (direct access)"
image: "ghcr.io/jmservera/{arch}-addon-casabot"
options:
  system_packages: []
  init_commands: []
schema:
  leave_front_door_open: bool?
  system_packages:
    - str
  init_commands:
    - str